/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoanPaymentCntl;
import javax.swing.JOptionPane;

/**
 *
 * @author Aung Nay
 */
public class LoanPaymentUI extends javax.swing.JFrame {
    private LoanPaymentCntl loanPayCntl;
    
    /**
     * Creates new form LoanPaymentUI
     */
    public LoanPaymentUI(LoanPaymentCntl loanCntl) {
        this.loanPayCntl = loanCntl;
        initComponents();
    }
    
    public boolean comfirmDelete(){        
        int option = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete your loan request?", 
                "Delete confirmation", JOptionPane.YES_NO_OPTION);
        return option == 0;
    }
    
    public void loanRequestFormDeleteCheck() {
        JOptionPane.showMessageDialog(rootPane, "Cannot Delete Approved Loan Request.", 
                "Loan Request Delete Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void hidePaymentOptions(){
        payBtn.setVisible(false);
        makePaymentBtn.setVisible(false);
        jTextFieldPaymentAmount.setVisible(false);
        jLabelAmountNumber.setVisible(false);
        jLabelAmountNumber2.setVisible(false);
        jLabelAmountDue.setVisible(false);
        jTableLoanRequestDetail.setVisible(false);
        jTableLoanRequestDetail.setTableHeader(null);
    }
    
    public void hideDetailOptions() {
        deleteLoanBtn.setVisible(false);
        jTableLoanShowDetail.setVisible(false);
        jTableLoanShowDetail.setTableHeader(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLoanRequestDetail = new javax.swing.JTable();
        makePaymentBtn = new javax.swing.JButton();
        jTextFieldPaymentAmount = new javax.swing.JTextField();
        jLabelAmountDue = new javax.swing.JLabel();
        jLabelAmountNumber = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        deleteLoanBtn = new javax.swing.JButton();
        jLabelAmountNumber2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLoanShowDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableLoanRequestDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Loan ID", "Loan Type", "Loan Amount", "Principal", "Interest", "Fee"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLoanRequestDetail);
        if (jTableLoanRequestDetail.getColumnModel().getColumnCount() > 0) {
            jTableLoanRequestDetail.getColumnModel().getColumn(0).setResizable(false);
            jTableLoanRequestDetail.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableLoanRequestDetail.getColumnModel().getColumn(1).setResizable(false);
            jTableLoanRequestDetail.getColumnModel().getColumn(2).setResizable(false);
            jTableLoanRequestDetail.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableLoanRequestDetail.getColumnModel().getColumn(3).setResizable(false);
            jTableLoanRequestDetail.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableLoanRequestDetail.getColumnModel().getColumn(4).setResizable(false);
            jTableLoanRequestDetail.getColumnModel().getColumn(5).setResizable(false);
        }

        makePaymentBtn.setText("Make Payment");

        jTextFieldPaymentAmount.setToolTipText("Enter the amount you want to pay");

        jLabelAmountDue.setFont(new java.awt.Font("Gulim", 1, 14)); // NOI18N
        jLabelAmountDue.setText("Amount Due");

        jLabelAmountNumber.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabelAmountNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAmountNumber.setText("$");

        payBtn.setText("Pay");

        backBtn.setText("Back");

        deleteLoanBtn.setText("Delete Loan Request");

        jLabelAmountNumber2.setFont(new java.awt.Font("Gulim", 1, 18)); // NOI18N
        jLabelAmountNumber2.setToolTipText("");

        jTableLoanShowDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Loan ID", "Loan Type", "Loan Amount", "Principal", "Loan Term (days)", "Interest", "Fee", "Secured", "Approved"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableLoanShowDetail);
        if (jTableLoanShowDetail.getColumnModel().getColumnCount() > 0) {
            jTableLoanShowDetail.getColumnModel().getColumn(0).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableLoanShowDetail.getColumnModel().getColumn(1).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(2).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableLoanShowDetail.getColumnModel().getColumn(3).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableLoanShowDetail.getColumnModel().getColumn(4).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(5).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(6).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(7).setResizable(false);
            jTableLoanShowDetail.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAmountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelAmountNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(deleteLoanBtn)
                                        .addGap(141, 141, 141)
                                        .addComponent(makePaymentBtn))
                                    .addComponent(jTextFieldPaymentAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makePaymentBtn)
                            .addComponent(deleteLoanBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAmountDue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAmountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAmountNumber2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(payBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backBtn;
    public javax.swing.JButton deleteLoanBtn;
    private javax.swing.JLabel jLabelAmountDue;
    private javax.swing.JLabel jLabelAmountNumber;
    private javax.swing.JLabel jLabelAmountNumber2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableLoanRequestDetail;
    public javax.swing.JTable jTableLoanShowDetail;
    private javax.swing.JTextField jTextFieldPaymentAmount;
    public javax.swing.JButton makePaymentBtn;
    public javax.swing.JButton payBtn;
    // End of variables declaration//GEN-END:variables
}
